/// ARB namespace merger for flutter_ui_kit_l10n.
///
/// Merges all namespace ARB files (l10n/namespaces/*_{locale}.arb) into
/// a single ARB file per locale (l10n/ui_kit_{locale}.arb).
///
/// Run via: dart run tool/merge_arb.dart
/// Or via melos: melos l10n:merge
///
/// Namespace order (later namespaces override earlier ones on key conflict):
///   1. core
///   2. settings
///   (Add new namespaces to [_namespaces] below)
library;

import 'dart:convert';
import 'dart:io';

const _namespaces = [
  'auth',
  'common',  
  'core', 
  'notice',
  'settings', 
  'time',
  'validation', 
];
const _locales = ['en', 'ko', 'ja'];
const _arbDir = 'l10n';
const _namespaceDir = 'l10n/namespaces';

void main() {
  for (final locale in _locales) {
    _mergeLocale(locale);
  }
  stdout.writeln('✓ ARB merge complete.');
}

void _mergeLocale(String locale) {
  final merged = <String, dynamic>{
    '@@locale': locale,
    '@@description':
        'Merged ARB — auto-generated by tool/merge_arb.dart. Do not edit manually.',
  };

  for (final ns in _namespaces) {
    final file = File('$_namespaceDir/${ns}_$locale.arb');
    if (!file.existsSync()) {
      stderr.writeln('  [WARN] Missing: ${file.path} — skipping');
      continue;
    }

    final content = file.readAsStringSync();
    final Map<String, dynamic> data =
        jsonDecode(content) as Map<String, dynamic>;

    for (final entry in data.entries) {
      // Skip @@-prefixed metadata keys from namespace files (we set them above)
      if (entry.key.startsWith('@@')) continue;
      merged[entry.key] = entry.value;
    }

    stdout.writeln('  merged: ${file.path}');
  }

  final output = File('$_arbDir/ui_kit_$locale.arb');
  const encoder = JsonEncoder.withIndent('  ');
  output.writeAsStringSync('${encoder.convert(merged)}\n');
  stdout.writeln('  → wrote: ${output.path}');
}
