name: show_case_theme
description: "Design system showcase app for flutter_ui_kit_theme."
publish_to: 'none'

version: 1.1.0

environment:
  sdk: ^3.10.7

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_ui_kit_theme: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
