name: flutter_ui_kit
publish_to: none
environment:
  sdk: ">=3.5.0 <4.0.0"
dev_dependencies:
  melos: ^7.4.0
workspace:
  - packages/flutter_ui_kit_google_mobile_ads
  - packages/flutter_ui_kit_chat
  - packages/flutter_ui_kit_theme
  # - apps/show_case_theme